// Generated by Wrangler on Wed Oct 30 2024 17:41:11 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

export interface Env {
  DATABASE_URL: string;
  TURSO_AUTH_TOKEN: string;
}
