workers_dev = true
name = "tutorial-search"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat_v2"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "tutorial-search-db"
database_id = "your-database-id"
migrations_dir = "migrations"

[vars]
CLOUDFLARE_ACCOUNT_ID="account-id"
CLOUDFLARE_TOKEN="token"
DATABASE_ID="your-database-id"
PRODUCTION=false
SESSION_SECRET="secret"